name: aliyun_oss_dart_sdk
description: aliyun oss dart sdk
version: 0.0.1
homepage: https://github.com/FaKenKoala/aliyun_oss_dart_sdk.git

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  convert: ^3.0.1
  crclib: ^3.0.0
  crypto: ^3.0.1
  dio: ^4.0.4
  encrypt: ^5.0.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  path: ^1.8.1
  shared_preferences: ^2.0.12
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lints: ^1.0.0
  test: ^1.16.0
