name: aliyun_oss_dart_sdk
description: aliyun oss dart sdk
version: 0.0.1
homepage: https://github.com/FaKenKoala/aliyun_oss_dart_sdk.git

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  charset_converter: ^2.0.0
  crypto: ^3.0.1
  cryptography: ^2.0.5
  encrypt: ^5.0.1
  http: ^0.13.4
  intl: ^0.17.0
  xml: ^5.3.1
